# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MixedDeviOSProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MixedDeviOSProject

  pod 'Flutter', :podspec => 'mixed_dev_flutter_app/Debug/Flutter.podspec'

  target 'MixedDeviOSProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MixedDeviOSProjectUITests' do
    # Pods for testing
  end

end
